### ISSUE TITLE
[question] risc-v support

### ISSUE THREAD

**Issue by XieJiSS** [boostorg/atomic#53]
Greetings,

Is there any plan for making `boost/atomic` compatible with RISC-V? This will be useful when trying to Implement lock-free data structures.

ref https://github.com/sfztools/sfizz/issues/1023#issuecomment-967231108

**Comment by Lastique** [comment]
Modern compilers provide intrinsics, which Boost.Atomic already use. If your compiler supports RISC-V then it should already be supported by Boost.Atomic.

There are a number of extended operations that are provided by Boost.Atomic and not directly covered by intrinsics. Those operations are emulated through intrinsics where a more specialized implementation is not present, which is the case for RISC-V. 

Currently, there are no plans to add a specialized assembler backend for RISC-V. I have no knowledge of RISC-V and no hardware to test.

**Comment by XieJiSS** [comment]
Thanks for the explanation.

**Comment by XieJiSS** [comment]
Hi @Lastique , if specifically, I want to patch `include/boost/atomic/detail/pause.hpp` locally, what might be the alternative for i386 `pause` and arm `yield`? Currently in RISC-V, we may only choose `nop` (since `pause` instruction is still in discussion), and I'm not sure whether it is ok to do so. Will this brings possible speed regression (which is acceptable in my use case), or completely breaks the `void pause()` function? Thanks!

**Comment by Lastique** [comment]
The `pause()` function is thus used to suspend current thread execution for some time without yielding to the OS kernel, which is useful in spin loops. The `pause` instruction in x86 is suspending execution on the current virtual core so that the sibling virtual core can proceed its execution faster (as it reduces contention for the execution units in the physical core). The `yield` instruction on ARM is also suspending execution of the current core for some amount of cycles. In both cases, the instruction also reduces power consumption, which lets CPU clocks to stay high.

I don't know if there is an instruction in RISC-V that has a similar effect to that of `pause` and `yield`. If there is, it should be used to implement `pause()`. If not, `pause()` should be left empty (which is how it is now).

Note that `nop` instructions are not equivalent to `pause` or `yield`. This instruction is typically used to align code, and CPUs are optimized to dispatch `nop` as fast as possible, so using `nop` would not suspend the thread for long enough. It would also not reduce power consumption since the CPU would be still decoding `nop` and other instructions at full tilt.
